### ISSUE TITLE
Impossible to pack properly

### ISSUE THREAD

**Issue by Mallow234** [Tinter/RusWepPack#1]
When packing is attempted with binarization using addon builder, the pbo is not built correctly - it is simply a file with a single config, and is in no way usable.

When packing is attempted without binarization, addon builder throws error code 1.

Perhaps using pboproject from mikero would fix this?

**Comment by Mallow234** [comment]
Attempted to pack with Mikero's tools but -they're still fucked captain-

Analysing the output may work but I'm not sure if it would reveal anything

**Comment by Mallow234** [comment]
Removing everything except the config still resulted in a fucked build, at this point I'm thinking it's either  BI fucking up addon builder or problems with github.

**Comment by Tinter** [comment]
Nothing can be done until a cause is found and it might just be on your end since it works for me.

**Comment by Mallow234** [comment]
This has been resolved
